# This file was generated by GoReleaser. DO NOT EDIT.
cask "verifi" do
  name "verifi"
  desc "Unified certificate management for developers"
  homepage "https://github.com/princespaghetti/verifi"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "verifi"

  on_macos do
    on_intel do
      url "https://github.com/princespaghetti/verifi/releases/download/v#{version}/verifi_#{version}_darwin_amd64.tar.gz"
      sha256 "b1244d6a3cb3a96140f90f2a1d789c08318ae654e86b97fb28bfc843e8ac4045"
    end
    on_arm do
      url "https://github.com/princespaghetti/verifi/releases/download/v#{version}/verifi_#{version}_darwin_arm64.tar.gz"
      sha256 "89dcda569705c72e3ffb9c52c17cfe4768cb5602b90086c0b1655c2df9e5cdfa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/princespaghetti/verifi/releases/download/v#{version}/verifi_#{version}_linux_amd64.tar.gz"
      sha256 "582dfaced73ae3c01192df6362c01becfd46a6def1c146919530acb3d3f44db9"
    end
    on_arm do
      url "https://github.com/princespaghetti/verifi/releases/download/v#{version}/verifi_#{version}_linux_arm64.tar.gz"
      sha256 "53c16425776d6f0fd088a10789d0aaf44c38a6104e95f79685cded63cceb7a14"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/verifi"]
    end
  end

  uninstall_postflight do
    system_command "sh", args: ["-c", "rm -rf ~/.verifi"]
  end

  # No zap stanza required
end
