# This file was generated by GoReleaser. DO NOT EDIT.
cask "verifi" do
  name "verifi"
  desc "Unified certificate management for developers"
  homepage "https://github.com/princespaghetti/verifi"
  version "0.1.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "verifi"

  on_macos do
    on_intel do
      url "https://github.com/princespaghetti/verifi/releases/download/v#{version}/verifi_#{version}_darwin_amd64.tar.gz"
      sha256 "e2920a1b80d4d83bfcf54e23f73c1a320c1a91f3bdf35c6cbb7b5208bcf5d704"
    end
    on_arm do
      url "https://github.com/princespaghetti/verifi/releases/download/v#{version}/verifi_#{version}_darwin_arm64.tar.gz"
      sha256 "1e9bfddc7017b3ad9506ece48ab63ad2b5383f35bde836e54639636c5597e6aa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/princespaghetti/verifi/releases/download/v#{version}/verifi_#{version}_linux_amd64.tar.gz"
      sha256 "63fe9c9cc125f482b6eb9251395ded67005cd75d59595dc8af48af600c07f532"
    end
    on_arm do
      url "https://github.com/princespaghetti/verifi/releases/download/v#{version}/verifi_#{version}_linux_arm64.tar.gz"
      sha256 "4847fb68c2330be13c5a571ec2601ce3bc6f84ddf8d088e8e6f6cfce9a68e5d9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/verifi"]
    end
  end

  uninstall_postflight do
    system_command "sh", args: ["-c", "rm -rf ~/.verifi"]
  end

  # No zap stanza required
end
