# This file was generated by GoReleaser. DO NOT EDIT.
cask "verifi" do
  name "verifi"
  desc "Unified certificate management for developers"
  homepage "https://github.com/princespaghetti/verifi"
  version "0.1.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "verifi"

  on_macos do
    on_intel do
      url "https://github.com/princespaghetti/verifi/releases/download/v#{version}/verifi_#{version}_darwin_amd64.tar.gz"
      sha256 "983435ec888d6d33670f0e47bf510438c3e719d7426a8790a1fde93853e4d7f3"
    end
    on_arm do
      url "https://github.com/princespaghetti/verifi/releases/download/v#{version}/verifi_#{version}_darwin_arm64.tar.gz"
      sha256 "fe2ad875b0cf33d1c501ae1b1d8f98e22e5c9d13ab9cf9d3dd575c77908936ae"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/princespaghetti/verifi/releases/download/v#{version}/verifi_#{version}_linux_amd64.tar.gz"
      sha256 "9fa616bf795a4c50ada9be2f8260530096b9b9e06c347a9b106426d338e8655b"
    end
    on_arm do
      url "https://github.com/princespaghetti/verifi/releases/download/v#{version}/verifi_#{version}_linux_arm64.tar.gz"
      sha256 "265f16c734dd83820b71debcc917dc8be538176788f46cc5941a9e0db26f11a0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/verifi"]
    end
  end

  uninstall_postflight do
    system_command "sh", args: ["-c", "rm -rf ~/.verifi"]
  end

  # No zap stanza required
end
