# This file was generated by GoReleaser. DO NOT EDIT.
cask "verifi" do
  name "verifi"
  desc "Unified certificate management for developers"
  homepage "https://github.com/princespaghetti/verifi"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "verifi"

  on_macos do
    on_intel do
      url "https://github.com/princespaghetti/verifi/releases/download/v#{version}/verifi_#{version}_darwin_amd64.tar.gz"
      sha256 "077b9a7b67031a533c7049e66d07154fd03e3c0700b0b0692e68a66c706c7a3e"
    end
    on_arm do
      url "https://github.com/princespaghetti/verifi/releases/download/v#{version}/verifi_#{version}_darwin_arm64.tar.gz"
      sha256 "fa93b27b869ed53a5c69fc62d2c6bd0631117b1eeb3ce43f88f1f476be0bc115"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/princespaghetti/verifi/releases/download/v#{version}/verifi_#{version}_linux_amd64.tar.gz"
      sha256 "edd9d717fb61b4ed701412b6cfa70ed8aef60d7b888a64baa55892af845059e3"
    end
    on_arm do
      url "https://github.com/princespaghetti/verifi/releases/download/v#{version}/verifi_#{version}_linux_arm64.tar.gz"
      sha256 "954db47195eb7dd86f78b91c319c89ece2810785b86a289cb37c8cd765c920f0"
    end
  end

  # No zap stanza required
end
